(wip)

diff --git a/script/efr32-definitions b/script/efr32-definitions
--- a/script/efr32-definitions
+++ b/script/efr32-definitions
@@ -41,12 +41,6 @@ if [ -z ${repo_dir+x} ]; then
     script_dir="$(realpath "$(dirname "${script_path}")")"
     repo_dir="$(dirname "${script_dir}")"
 fi
-# Check if sdk_dir is defined
-if [ -z ${sdk_dir+x} ]; then
-    # Error if sdk_dir is not defined
-    echo "Error: sdk_dir is not defined" >&2
-    exit 1
-fi
 
 efr32_device_regex=""
 efr32_device_regex+="\(efr32\)*"                               # Group 1 - efr32 (optional)
@@ -69,11 +63,14 @@ efr32_get_board_slcc()
         doc="Gets the latest revision .slcc file for a efr32 board"
     #
     # Arg $1 -- efr32 board
-    if [ $# -ne 1 ] || [ -z "$1" ]; then
+    # Arg $2 -- SDK directory (optional)
+    if [ $# -lt 1 ] || [ -z "$1" ]; then
         printf "%s\n\nUsage:\n\t%s <efr32_board> \n" "${doc}" "${FUNCNAME[0]}" >&2
         return 1
     fi
+
     local board=$1
+    local sdk_dir=${sdk_dir-$2}
 
     # Find component file for latest revision of board
     local board_slcc
@@ -88,10 +85,11 @@ efr32_get_board_slcc()
 efr32_get_platform()
 {
     local board=${board-$1}
+    local sdk_dir=${sdk_dir:-$2}
 
     # Find component file for latest revision of board
     local board_slcc
-    board_slcc=$(efr32_get_board_slcc "${board}")
+    board_slcc=$(efr32_get_board_slcc "${board}" "${sdk_dir}")
 
     # Determine board's platform and exit if unsupported
     local platform
@@ -101,16 +99,12 @@ efr32_get_platform()
             | head -n 1
     )
 
-    if [ -z "${platform}" ]; then
-        echo "Error parsing platform"
-        exit 3
-    fi
-
     echo "${platform}"
 }
 
 efr32_get_platforms()
 {
+    # TODO:
     local platform_dir="$repo_dir/src" \
         && find "$platform_dir" -type d -name '*efr32*' -exec basename {} \; | sort
 }
@@ -132,8 +126,8 @@ efr32_check_platform()
 
     if ! $match; then
         set +x
-        printf "\n\nERROR: Invalid platform\n" >&2
-        printf "Valid platforms:\n" >&2
+        printf "\n\nERROR: Unsupported platform\n" >&2
+        printf "Supported platforms:\n" >&2
         for platform in $(efr32_get_platforms); do
             printf " - %s\n" "${platform}" >&2
         done
